---
service: es-aggregation-sg
provider:
  name: aws
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-county-wrangler:
    name: es-aggregation-county-wrangler
    handler: aggregation_county_wrangler.lambda_handler
    package:
      include:
        - aggregation_county_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      bucket_name: results-s3-bucket
      file_name: county_out.json
      queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo
      checkpoint: 4
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_messageid_name: byCountyAgg
      method_name: es-aggregation_county_method
      period: 201809
      s3_file: imputation_apply_out.json
      arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      incoming_message_group: apply_factors_out

  deploy-county-method:
    name: es-aggregation_county_method
    handler: aggregation_county_method.lambda_handler
    package:
      include:
        - aggregation_county_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results

  deploy-entref-wrangler:
    name: es-aggregation-entref-wrangler
    handler: aggregation_entref_wrangler.lambda_handler
    package:
      include:
        - aggregation_entref_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      bucket_name: results-s3-bucket
      file_name: ent_ref_out.json
      queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo
      checkpoint: 4
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_messageid_name: byEntRefAgg
      method_name: aggregation_entref_method
      period: 201809
      s3_file: imputation_apply_out.json
      arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      incoming_message_group: apply_factors_out

  deploy-entref-method:
    name: es-aggregation-entref-method
    handler: aggregation_entref_method.lambda_handler
    package:
      include:
        - aggregation_entref_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results

  deploy-top2-wrangler:
    name: es-aggregation-top2-wrangler
    handler: aggregation_top2_wrangler.lambda_handler
    package:
      include:
        - aggregation_top2_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      bucket_name: results-s3-bucket
      file_name: top2_out.json
      queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo
      checkpoint: 4
      arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_messageid_name: byTop2Agg
      method_name: aggregation_top2_method
      s3_file: imputation_apply_out.json
      arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      incoming_message_group: apply_factors_out

  deploy-top2-method:
    name: es-aggregation-top2-method
    handler: aggregation_top2_wrangler.lambda_handler
    package:
      include:
        - aggregation_top2_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results

  deploy-combiner:
    name: es-aggregation-combiner
    handler: combiner.lambda_handler
    package:
      include:
        - combiner.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      bucket_name: results-s3-bucket
      checkpoint: 4
      file_name: aggergation_out.json
      queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo
      sqs_messageid_name: agg_combiner
      s3_file: top2_out.json