---
service: es-aggregation-sg
provider:
  name: aws
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  memorySize: 1024
  timeout: 20
  tracing:
    lambda: true
  package:
    individually: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-bricks-splitter-wrangler:
    name: es-aggregation-bricks-splitter-wrangler
    handler: aggregation_bricks_splitter_wrangler.lambda_handler
    package:
      include:
        - aggregation_bricks_splitter_wrangler.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      out_file_name_brick: aggregation_brick_prep_out.json
      out_file_name_region: aggregation_region_prep_out.json
      method_name: es-add-regionless-method
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults

  deploy-column-wrangler:
    name: es-aggregation-column-wrangler
    handler: aggregation_column_wrangler.lambda_handler
    package:
      include:
        - aggregation_column_wrangler.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      out_file_name: aggregation_column_out.json
      method_name: es-aggregation-column-method
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: aggregation-by-county

  deploy-column-method:
    name: es-aggregation-column-method
    handler: aggregation_column_method.lambda_handler
    package:
      include:
        - aggregation_column_method.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
    tags:
      app: results

  deploy-top2-wrangler:
    name: es-aggregation-top2-wrangler
    handler: aggregation_top2_wrangler.lambda_handler
    package:
      include:
        - aggregation_top2_wrangler.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      method_name: es-aggregation-top2-method
      out_file_name: top2_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: aggregation-by-top2

  deploy-top2-method:
    name: es-aggregation-top2-method
    handler: aggregation_top2_method.lambda_handler
    package:
      include:
        - aggregation_top2_method.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
    tags:
      app: results

  deploy-combiner:
    name: es-aggregation-combiner
    handler: combiner.lambda_handler
    package:
      include:
        - combiner.py
      exclude:
        - ./**
      individually: true
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      out_file_name: aggregation_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: aggregation-combiner-out

plugins:
  - serverless-latest-layer-version
