---
service: es-aggregation-sg
provider:
  name: aws
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  tracing:
    lambda: true
  package:
    individually: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-county-wrangler:
    name: es-aggregation-county-wrangler
    handler: aggregation_county_wrangler.lambda_handler
    package:
      include:
        - aggregation_county_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      in_file_name: imputation_apply_out.json
      out_file_name: aggregation_county_out.json
      method_name: es-aggregation-county-method
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: aggregation-by-county
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-county-method:
    name: es-aggregation-county-method
    handler: aggregation_county_method.lambda_handler
    package:
      include:
        - aggregation_county_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results

  deploy-entref-wrangler:
    name: es-aggregation-entref-wrangler
    handler: aggregation_entref_wrangler.lambda_handler
    package:
      include:
        - aggregation_entref_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      in_file_name: imputation_apply_out.json
      method_name: es-aggregation-entref-method
      out_file_name: ent_ref_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: aggregation-by-entref
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-entref-method:
    name: es-aggregation-entref-method
    handler: aggregation_entref_method.lambda_handler
    package:
      include:
        - aggregation_entref_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results

  deploy-top2-wrangler:
    name: es-aggregation-top2-wrangler
    handler: aggregation_top2_wrangler.lambda_handler
    package:
      include:
        - aggregation_top2_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      in_file_name: imputation_apply_out.json
      method_name: es-aggregation-top2-method
      out_file_name: top2_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: aggregation-by-top2
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-top2-method:
    name: es-aggregation-top2-method
    handler: aggregation_top2_method.lambda_handler
    package:
      include:
        - aggregation_top2_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results

  deploy-combiner:
    name: es-aggregation-combiner
    handler: combiner.lambda_handler
    package:
      include:
        - combiner.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 4
      bucket_name: results-s3-bucket
      in_file_name: non_responders_output.json
      out_file_name: aggregation_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: aggregation-combiner-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo
